apiVersion: v1
kind: Service
metadata:
  name: se-lab-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # Optional; Kubernetes will assign a port if not specified
  selector:
    app: se-lab-app
